# Cobalt 配置文件
# 支持多种配置项，可灵活扩展

# Marketplace 数据源配置
marketplace:
  sources:
    # 官方数据源
    - name: Anthropic 官方技能
      url: https://github.com/anthropics/anthropic-skills
      description: Anthropic 官方维护的 Claude Code 技能集合
      tags: [official, verified, anthropic]

    # 社区数据源
    - name: Agent Browser
      url: https://github.com/vercel-labs/agent-browser
      description: Vercel Labs 的浏览器自动化工具，支持 AI Agent 进行网页交互
      tags: [community, browser, automation, vercel]

# 未来可以添加其他配置
# plugins:
#   sources:
#     - name: ...
#       url: ...
#
# themes:
#   sources:
#     - name: ...
#       url: ...
#
# templates:
#   sources:
#     - name: ...
#       url: ...
